from ultralytics import YOLO
import argparse
import os
import sys

# Ensure src is in python path to import config if run directly
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src import config

def train(epochs=config.EPOCHS, batch_size=config.BATCH_SIZE, model_path='yolov8n.pt'):
    """
    Trains the YOLOv8 model.
    """
    print(f"Starting training with the following parameters:")
    print(f"Epochs: {epochs}")
    print(f"Batch Size: {batch_size}")
    print(f"Model: {model_path}")
    
    # Load a model
    model = YOLO(model_path)  # load a pretrained model (recommended for training)

    # Use the data.yaml generated by data_setup.py in the project root
    data_yaml_path = os.path.join(config.BASE_DIR, 'data.yaml')
    
    if not os.path.exists(data_yaml_path):
        print(f"Error: {data_yaml_path} not found. Please run src/data_setup.py first.")
        return

    # Train the model
    results = model.train(
        data=data_yaml_path,
        epochs=epochs,
        batch=batch_size,
        imgsz=config.IMAGE_SIZE,
        project=os.path.join(config.BASE_DIR, 'runs/detect'),
        name='yolov8_military_vehicles'
    )
    
    print("Training completed successfully.")
    print(f"Results saved to {results.save_dir}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Train YOLOv8 model for Military Vehicle Detection')
    parser.add_argument('--epochs', type=int, default=config.EPOCHS, help='Number of epochs to train for')
    parser.add_argument('--batch-size', type=int, default=config.BATCH_SIZE, help='Batch size for training')
    parser.add_argument('--model', type=str, default='yolov8n.pt', help='Pretrained model path or name (e.g. yolov8n.pt, yolov8s.pt)')
    
    args = parser.parse_args()
    
    train(epochs=args.epochs, batch_size=args.batch_size, model_path=args.model)
